aaa

diff --git a/k8s/testlab/whatsmyip/deployment.yaml b/k8s/testlab/whatsmyip/deployment.yaml
--- a/k8s/testlab/whatsmyip/deployment.yaml
+++ b/k8s/testlab/whatsmyip/deployment.yaml
@@ -26,7 +26,7 @@ spec:
             - -c
             - |
               IP=`curl --socks5 http://localhost:9050 -L check.torproject.org/api/ip` 
-              echo "Curl succesfull, exiting ($IP)"
+              echo "Curl successful, exiting ($IP)"
         # - name: vpn
         #   image: qmcgaw/gluetun:v3.36.0
         #   restartPolicy: Always
@@ -47,6 +47,22 @@ spec:
         #       value: "on"
         #     - name: FIREWALL_OUTBOUND_SUBNETS
         #       value: "10.42.0.0/15" 
+            #   - name: OPENVPN_CUSTOM_CONFIG
+            #     value: "/gluetun/custom.conf"
+            # volumeMounts:
+            #   - name: vpnconfig
+            #     path: /gluetun/config.conf
+        # - name: ping
+        #   image: busybox
+        #   command:
+        #   - sh
+        #   - -c
+        #   - |
+        #     while ! ping -c 1 8.8.8.8; do
+        #       echo "Ping failed, retrying in 5"
+        #       sleep 5
+        #     done
+        #     echo "ping succesfull, exiting"
       containers:
         - name: whatsmyip
           image: yauritux/busybox-curl
@@ -54,3 +70,6 @@ spec:
           imagePullPolicy: Always
           ports:
             - containerPort: 8080
+      volumes:
+        - name: vpnconfig
+
